// Package contextfile writes per-project markdown context files to
// ~/.synapses/context/<hash>.md. These files are read by the Claude Code
// SessionStart hook to inject project identity and pending tasks into the
// agent's context automatically — without requiring the agent to call
// session_init() first.
package contextfile

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/SynapsesOS/synapses/internal/graph"
	"github.com/SynapsesOS/synapses/internal/store"
)

// fnvHash mirrors the FNV-1a computation from store.hashPath so that the
// context file can be located by its project path without importing store.
func fnvHash(path string) string {
	h := uint32(2166136261)
	for _, c := range []byte(path) {
		h ^= uint32(c)
		h *= 16777619
	}
	return fmt.Sprintf("%08x", h)
}

// ContextFilePath returns the absolute path of the context file for repoRoot.
// The directory (~/.synapses/context/) is created if it does not exist.
func ContextFilePath(repoRoot string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("locate home dir: %w", err)
	}
	dir := filepath.Join(home, ".synapses", "context")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("create context dir: %w", err)
	}
	return filepath.Join(dir, fnvHash(repoRoot)+".md"), nil
}

// Write renders and atomically writes the context file for repoRoot.
// identity and tasks may be nil/empty — the file is still written so the
// hook always finds something useful even if data is unavailable.
// All errors are returned to the caller; the daemon should discard them silently.
func Write(repoRoot string, identity *graph.ProjectIdentity, tasks []store.Task) error {
	path, err := ContextFilePath(repoRoot)
	if err != nil {
		return err
	}
	content := render(identity, tasks)
	// Atomic write: temp file + rename avoids a partial read by the hook.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write context file: %w", err)
	}
	return os.Rename(tmp, path)
}

// render produces the markdown content for the context file.
func render(identity *graph.ProjectIdentity, tasks []store.Task) string {
	var b strings.Builder
	b.WriteString("<!-- Auto-generated by Synapses daemon. Do not edit. -->\n")

	if identity != nil {
		b.WriteString(fmt.Sprintf("# Synapses — %s\n\n", identity.RepoID))
		b.WriteString(fmt.Sprintf(
			"**Scale**: %s (%d files, %d functions, %d edges)\n\n",
			identity.Scale,
			identity.Summary.Files,
			identity.Summary.Functions,
			identity.Summary.Edges,
		))
		if identity.ToolGuidance != "" {
			b.WriteString(fmt.Sprintf("> %s\n\n", identity.ToolGuidance))
		}
	}

	b.WriteString("## Pending Tasks\n")
	pending := filterPending(tasks)
	if len(pending) == 0 {
		b.WriteString("No pending tasks.\n")
	} else {
		for _, t := range pending {
			marker := "[ ]"
			if t.Status == "in_progress" {
				marker = "[~]"
			}
			b.WriteString(fmt.Sprintf("- %s **%s** (id: `%s`", marker, t.Title, t.ID))
			if t.Priority != "" && t.Priority != "p2" {
				b.WriteString(fmt.Sprintf(", priority: %s", t.Priority))
			}
			b.WriteString(")\n")
			if t.Description != "" {
				b.WriteString(fmt.Sprintf("  _%s_\n", t.Description))
			}
		}
	}
	b.WriteString("\n")

	b.WriteString("## Workflow\n")
	b.WriteString("```\nsession_init → prepare_context → validate_plan → edit files → verify_implementation\n```\n\n")

	b.WriteString("## Key Tools\n")
	b.WriteString("| Goal | Tool |\n|---|---|\n")
	b.WriteString("| Understand a function | `get_context(entity=\"Name\")` |\n")
	b.WriteString("| Find a symbol | `find_entity(query=\"name\")` |\n")
	b.WriteString("| Search by concept | `search(query=\"...\", mode=\"semantic\")` |\n")
	b.WriteString("| Trace call chain | `get_call_chain(from=\"A\", to=\"B\")` |\n")
	b.WriteString("| Find what breaks | `get_impact(symbol=\"Name\")` |\n")
	b.WriteString("| Before multi-file edits | `validate_plan(changes=[...])` |\n")
	b.WriteString("| After writing files | `verify_implementation(files_written=[\"...\"])` |\n")
	b.WriteString("| Book a scope | `claim_work(agent_id=\"...\", scope=\"pkg/...\")` |\n")
	b.WriteString("| Create tasks | `create_plan(title=\"...\", tasks=[...])` |\n")

	b.WriteString(fmt.Sprintf("\n_Updated: %s_\n", time.Now().UTC().Format("2006-01-02 15:04 UTC")))
	return b.String()
}

// filterPending returns only tasks in pending or in_progress status.
func filterPending(tasks []store.Task) []store.Task {
	var out []store.Task
	for _, t := range tasks {
		if t.Status == "pending" || t.Status == "in_progress" {
			out = append(out, t)
		}
	}
	return out
}
