package contextfile

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/SynapsesOS/synapses/internal/graph"
	"github.com/SynapsesOS/synapses/internal/store"
)

// ── fnvHash ───────────────────────────────────────────────────────────────────

func TestFnvHash_Deterministic(t *testing.T) {
	h1 := fnvHash("/home/user/myproject")
	h2 := fnvHash("/home/user/myproject")
	if h1 != h2 {
		t.Errorf("fnvHash not deterministic: %q != %q", h1, h2)
	}
}

func TestFnvHash_DifferentPaths(t *testing.T) {
	h1 := fnvHash("/home/user/projectA")
	h2 := fnvHash("/home/user/projectB")
	if h1 == h2 {
		t.Errorf("fnvHash collision for different paths: both = %q", h1)
	}
}

func TestFnvHash_Format(t *testing.T) {
	h := fnvHash("/any/path")
	if len(h) != 8 {
		t.Errorf("expected 8-char hex hash, got %q (len %d)", h, len(h))
	}
	for _, c := range h {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			t.Errorf("non-hex char %q in hash %q", c, h)
		}
	}
}

// ── filterPending ─────────────────────────────────────────────────────────────

func TestFilterPending_KeepsPendingAndInProgress(t *testing.T) {
	tasks := []store.Task{
		{ID: "1", Status: "pending"},
		{ID: "2", Status: "in_progress"},
		{ID: "3", Status: "done"},
		{ID: "4", Status: "cancelled"},
	}
	got := filterPending(tasks)
	if len(got) != 2 {
		t.Fatalf("expected 2 tasks, got %d", len(got))
	}
	if got[0].ID != "1" || got[1].ID != "2" {
		t.Errorf("unexpected tasks: %v", got)
	}
}

func TestFilterPending_EmptyInput(t *testing.T) {
	if got := filterPending(nil); len(got) != 0 {
		t.Errorf("expected empty, got %v", got)
	}
}

func TestFilterPending_AllDone(t *testing.T) {
	tasks := []store.Task{
		{ID: "1", Status: "done"},
		{ID: "2", Status: "cancelled"},
	}
	if got := filterPending(tasks); len(got) != 0 {
		t.Errorf("expected empty, got %v", got)
	}
}

// ── render ────────────────────────────────────────────────────────────────────

func TestRender_AlwaysContainsAutoGenComment(t *testing.T) {
	out := render(nil, nil)
	if !strings.Contains(out, "Auto-generated by Synapses daemon") {
		t.Errorf("missing auto-gen comment in:\n%s", out)
	}
}

func TestRender_AlwaysContainsWorkflowSection(t *testing.T) {
	out := render(nil, nil)
	if !strings.Contains(out, "session_init") {
		t.Error("missing workflow section")
	}
	if !strings.Contains(out, "verify_implementation") {
		t.Error("missing verify_implementation in workflow")
	}
}

func TestRender_AlwaysContainsKeyToolsTable(t *testing.T) {
	out := render(nil, nil)
	for _, tool := range []string{"get_context", "find_entity", "validate_plan", "claim_work"} {
		if !strings.Contains(out, tool) {
			t.Errorf("missing tool %q in key tools table", tool)
		}
	}
}

func TestRender_NoIdentity_NoPendingTasks(t *testing.T) {
	out := render(nil, nil)
	if !strings.Contains(out, "No pending tasks.") {
		t.Errorf("expected 'No pending tasks.' when tasks=nil, got:\n%s", out)
	}
	// No identity section should appear.
	if strings.Contains(out, "# Synapses —") {
		t.Error("unexpected identity header when identity=nil")
	}
}

func TestRender_WithIdentity(t *testing.T) {
	id := &graph.ProjectIdentity{
		RepoID: "myrepo",
		Scale:  graph.ScaleLarge,
		Summary: graph.GraphSummary{
			Files:     42,
			Functions: 300,
			Edges:     1200,
		},
		ToolGuidance: "Always use Synapses tools at this scale.",
	}
	out := render(id, nil)
	if !strings.Contains(out, "# Synapses — myrepo") {
		t.Errorf("missing project header, got:\n%s", out)
	}
	if !strings.Contains(out, "large") {
		t.Error("missing scale in output")
	}
	if !strings.Contains(out, "42") {
		t.Error("missing file count")
	}
	if !strings.Contains(out, "300") {
		t.Error("missing function count")
	}
	if !strings.Contains(out, "1200") {
		t.Error("missing edge count")
	}
	if !strings.Contains(out, "Always use Synapses tools at this scale.") {
		t.Error("missing tool guidance")
	}
}

func TestRender_WithTasks_PendingAndInProgress(t *testing.T) {
	tasks := []store.Task{
		{ID: "t1", Title: "Fix auth bug", Status: "pending", Priority: "p0"},
		{ID: "t2", Title: "Add logging", Status: "in_progress", Description: "Use structured logs"},
		{ID: "t3", Title: "Old task", Status: "done"},
	}
	out := render(nil, tasks)

	// pending task with p0 priority
	if !strings.Contains(out, "[ ]") {
		t.Error("missing '[ ]' marker for pending task")
	}
	if !strings.Contains(out, "Fix auth bug") {
		t.Error("missing pending task title")
	}
	if !strings.Contains(out, "priority: p0") {
		t.Error("missing priority p0")
	}

	// in_progress task
	if !strings.Contains(out, "[~]") {
		t.Error("missing '[~]' marker for in_progress task")
	}
	if !strings.Contains(out, "Add logging") {
		t.Error("missing in_progress task title")
	}
	if !strings.Contains(out, "Use structured logs") {
		t.Error("missing task description")
	}

	// done task should not appear
	if strings.Contains(out, "Old task") {
		t.Error("done task should not appear in output")
	}
}

func TestRender_DefaultPriority_NotShown(t *testing.T) {
	tasks := []store.Task{
		{ID: "t1", Title: "Normal task", Status: "pending", Priority: "p2"},
	}
	out := render(nil, tasks)
	if strings.Contains(out, "priority:") {
		t.Error("p2 (default) priority should not be shown")
	}
}

func TestRender_ContainsUpdatedTimestamp(t *testing.T) {
	out := render(nil, nil)
	if !strings.Contains(out, "_Updated:") {
		t.Error("missing updated timestamp")
	}
}

// ── Write + ContextFilePath ───────────────────────────────────────────────────

func TestWrite_CreatesFileAndContent(t *testing.T) {
	// Override HOME so we don't pollute the real ~/.synapses/context/.
	tmp := t.TempDir()
	t.Setenv("HOME", tmp)

	repoRoot := "/tmp/test-project"
	if err := Write(repoRoot, nil, nil); err != nil {
		t.Fatalf("Write failed: %v", err)
	}

	path, err := ContextFilePath(repoRoot)
	if err != nil {
		t.Fatalf("ContextFilePath failed: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("file not found at %s: %v", path, err)
	}
	if !strings.Contains(string(data), "Auto-generated by Synapses daemon") {
		t.Error("file missing expected content")
	}
}

func TestWrite_AtomicNoPanicOnDoubleWrite(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("HOME", tmp)

	repoRoot := "/tmp/test-project-atomic"
	for i := 0; i < 3; i++ {
		if err := Write(repoRoot, nil, nil); err != nil {
			t.Fatalf("Write #%d failed: %v", i, err)
		}
	}
}

func TestContextFilePath_IsInsideSynapsesContext(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("HOME", tmp)

	path, err := ContextFilePath("/some/project")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expected := filepath.Join(tmp, ".synapses", "context")
	if !strings.HasPrefix(path, expected) {
		t.Errorf("expected path under %s, got %s", expected, path)
	}
	if !strings.HasSuffix(path, ".md") {
		t.Errorf("expected .md suffix, got %s", path)
	}
}

func TestContextFilePath_DifferentProjectsDifferentFiles(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("HOME", tmp)

	p1, _ := ContextFilePath("/project/alpha")
	p2, _ := ContextFilePath("/project/beta")
	if p1 == p2 {
		t.Errorf("different projects produced same context file path: %s", p1)
	}
}

func TestContextFilePath_SameProjectSamePath(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("HOME", tmp)

	p1, _ := ContextFilePath("/project/gamma")
	p2, _ := ContextFilePath("/project/gamma")
	if p1 != p2 {
		t.Errorf("same project produced different paths: %s vs %s", p1, p2)
	}
}
