// Package contextfile writes per-project markdown context files to
// ~/.synapses/context/<hash>.md. These files are read by the Claude Code
// SessionStart hook to inject project identity and pending tasks into the
// agent's context automatically — without requiring the agent to call
// session_init() first.
package contextfile

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/SynapsesOS/synapses/internal/graph"
	"github.com/SynapsesOS/synapses/internal/store"
)

// fnvHash mirrors the FNV-1a 64-bit computation from store.hashPath so that the
// context file can be located by its project path without importing store.
func fnvHash(path string) string {
	h := uint64(14695981039346656037)
	for _, c := range []byte(path) {
		h ^= uint64(c)
		h *= 1099511628211
	}
	return fmt.Sprintf("%016x", h)
}

// ContextFilePath returns the absolute path of the context file for repoRoot.
// The directory (~/.synapses/context/) is created if it does not exist.
func ContextFilePath(repoRoot string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("locate home dir: %w", err)
	}
	dir := filepath.Join(home, ".synapses", "context")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("create context dir: %w", err)
	}
	return filepath.Join(dir, fnvHash(repoRoot)+".md"), nil
}

// Write renders and atomically writes the context file for repoRoot.
// identity and tasks may be nil/empty — the file is still written so the
// hook always finds something useful even if data is unavailable.
// All errors are returned to the caller; the daemon should discard them silently.
func Write(repoRoot string, identity *graph.ProjectIdentity, tasks []store.Task) error {
	path, err := ContextFilePath(repoRoot)
	if err != nil {
		return err
	}
	content := render(identity, tasks)
	// Atomic write: temp file + rename avoids a partial read by the hook.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write context file: %w", err)
	}
	return os.Rename(tmp, path)
}

// render produces the markdown content for the context file.
// Intentionally minimal — the full session state (tasks, events, identity) is
// delivered by session_init(). This file exists only to orient the agent with
// scale before the first tool call.
func render(identity *graph.ProjectIdentity, tasks []store.Task) string {
	var b strings.Builder
	b.WriteString("<!-- Auto-generated by Synapses daemon. Do not edit. -->\n")

	if identity != nil {
		b.WriteString(fmt.Sprintf("# Synapses — %s\n\n", identity.RepoID))
		b.WriteString(fmt.Sprintf(
			"**Scale**: %s (%d files, %d functions, %d edges)\n\n",
			identity.Scale,
			identity.Summary.Files,
			identity.Summary.Functions,
			identity.Summary.Edges,
		))
		if identity.ToolGuidance != "" {
			b.WriteString(fmt.Sprintf("> %s\n\n", identity.ToolGuidance))
		}
	}

	// Show accurate task counts — full task list comes from session_init().
	pending := filterPending(tasks)
	inProgress := 0
	for _, t := range pending {
		if t.Status == "in_progress" {
			inProgress++
		}
	}
	trulyPending := len(pending) - inProgress
	if len(pending) > 0 {
		switch {
		case trulyPending > 0 && inProgress > 0:
			b.WriteString(fmt.Sprintf("**Tasks**: %d pending + %d in progress — call `session_init()` for details.\n\n", trulyPending, inProgress))
		case inProgress > 0:
			b.WriteString(fmt.Sprintf("**Tasks**: %d in progress — call `session_init()` for details.\n\n", inProgress))
		default:
			b.WriteString(fmt.Sprintf("**Tasks**: %d pending — call `session_init()` for details.\n\n", trulyPending))
		}
	}

	// Always include the session_init() call-to-action so agents know to start there.
	b.WriteString("Call `session_init()` to begin — returns full project state, tasks, and working state.\n\n")

	b.WriteString(fmt.Sprintf("_Updated: %s_\n", time.Now().UTC().Format("2006-01-02 15:04 UTC")))
	return b.String()
}

// filterPending returns only tasks in pending or in_progress status.
func filterPending(tasks []store.Task) []store.Task {
	var out []store.Task
	for _, t := range tasks {
		if t.Status == "pending" || t.Status == "in_progress" {
			out = append(out, t)
		}
	}
	return out
}
