package contextfile

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/SynapsesOS/synapses/internal/graph"
	"github.com/SynapsesOS/synapses/internal/store"
)

// ── fnvHash ───────────────────────────────────────────────────────────────────

func TestFnvHash_Deterministic(t *testing.T) {
	h1 := fnvHash("/home/user/myproject")
	h2 := fnvHash("/home/user/myproject")
	if h1 != h2 {
		t.Errorf("fnvHash not deterministic: %q != %q", h1, h2)
	}
}

func TestFnvHash_DifferentPaths(t *testing.T) {
	h1 := fnvHash("/home/user/projectA")
	h2 := fnvHash("/home/user/projectB")
	if h1 == h2 {
		t.Errorf("fnvHash collision for different paths: both = %q", h1)
	}
}

func TestFnvHash_Format(t *testing.T) {
	h := fnvHash("/any/path")
	if len(h) != 16 {
		t.Errorf("expected 16-char hex hash, got %q (len %d)", h, len(h))
	}
	for _, c := range h {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			t.Errorf("non-hex char %q in hash %q", c, h)
		}
	}
}

// ── filterPending ─────────────────────────────────────────────────────────────

func TestFilterPending_KeepsPendingAndInProgress(t *testing.T) {
	tasks := []store.Task{
		{ID: "1", Status: "pending"},
		{ID: "2", Status: "in_progress"},
		{ID: "3", Status: "done"},
		{ID: "4", Status: "cancelled"},
	}
	got := filterPending(tasks)
	if len(got) != 2 {
		t.Fatalf("expected 2 tasks, got %d", len(got))
	}
	if got[0].ID != "1" || got[1].ID != "2" {
		t.Errorf("unexpected tasks: %v", got)
	}
}

func TestFilterPending_EmptyInput(t *testing.T) {
	if got := filterPending(nil); len(got) != 0 {
		t.Errorf("expected empty, got %v", got)
	}
}

func TestFilterPending_AllDone(t *testing.T) {
	tasks := []store.Task{
		{ID: "1", Status: "done"},
		{ID: "2", Status: "cancelled"},
	}
	if got := filterPending(tasks); len(got) != 0 {
		t.Errorf("expected empty, got %v", got)
	}
}

// ── render ────────────────────────────────────────────────────────────────────

func TestRender_AlwaysContainsAutoGenComment(t *testing.T) {
	out := render(nil, nil)
	if !strings.Contains(out, "Auto-generated by Synapses daemon") {
		t.Errorf("missing auto-gen comment in:\n%s", out)
	}
}

func TestRender_AlwaysContainsWorkflowSection(t *testing.T) {
	out := render(nil, nil)
	// Minimal format: "session_init()" is referenced in the task count hint.
	// The workflow steps are no longer inlined — kept in CLAUDE.md instead.
	if !strings.Contains(out, "session_init") {
		t.Error("missing session_init reference")
	}
}

func TestRender_NoToolTableInMinimalFormat(t *testing.T) {
	// The context file is now minimal — tool tables live in CLAUDE.md, not here.
	out := render(nil, nil)
	for _, tool := range []string{"claim_work", "verify_implementation"} {
		if strings.Contains(out, tool) {
			t.Errorf("tool %q should not be in minimal context file", tool)
		}
	}
}

func TestRender_NoIdentity_NoPendingTasks(t *testing.T) {
	out := render(nil, nil)
	// Minimal format: no "No pending tasks." message, no identity header.
	if strings.Contains(out, "No pending tasks.") {
		t.Errorf("minimal format should not include 'No pending tasks.', got:\n%s", out)
	}
	if strings.Contains(out, "# Synapses —") {
		t.Error("unexpected identity header when identity=nil")
	}
}

func TestRender_WithIdentity(t *testing.T) {
	id := &graph.ProjectIdentity{
		RepoID: "myrepo",
		Scale:  graph.ScaleLarge,
		Summary: graph.GraphSummary{
			Files:     42,
			Functions: 300,
			Edges:     1200,
		},
		ToolGuidance: "Always use Synapses tools at this scale.",
	}
	out := render(id, nil)
	if !strings.Contains(out, "# Synapses — myrepo") {
		t.Errorf("missing project header, got:\n%s", out)
	}
	if !strings.Contains(out, "large") {
		t.Error("missing scale in output")
	}
	if !strings.Contains(out, "42") {
		t.Error("missing file count")
	}
	if !strings.Contains(out, "300") {
		t.Error("missing function count")
	}
	if !strings.Contains(out, "1200") {
		t.Error("missing edge count")
	}
	if !strings.Contains(out, "Always use Synapses tools at this scale.") {
		t.Error("missing tool guidance")
	}
}

func TestRender_WithTasks_ShowsCountNotDetails(t *testing.T) {
	tasks := []store.Task{
		{ID: "t1", Title: "Fix auth bug", Status: "pending", Priority: "p0"},
		{ID: "t2", Title: "Add logging", Status: "in_progress", Description: "Use structured logs"},
		{ID: "t3", Title: "Old task", Status: "done"},
	}
	out := render(nil, tasks)

	// Minimal format: shows accurate counts separately — "1 pending + 1 in progress".
	if !strings.Contains(out, "1 pending") {
		t.Errorf("expected '1 pending' task count, got:\n%s", out)
	}
	if !strings.Contains(out, "1 in progress") {
		t.Errorf("expected '1 in progress' count, got:\n%s", out)
	}
	// Must NOT say "2 pending" — that conflates in-progress tasks with pending.
	if strings.Contains(out, "2 pending") {
		t.Errorf("should not conflate in-progress tasks into pending count, got:\n%s", out)
	}
	if !strings.Contains(out, "session_init()") {
		t.Errorf("expected session_init() hint, got:\n%s", out)
	}

	// Task titles and descriptions must NOT appear — full list lives in session_init().
	for _, detail := range []string{"Fix auth bug", "Add logging", "Use structured logs", "Old task", "[ ]", "[~]"} {
		if strings.Contains(out, detail) {
			t.Errorf("task detail %q should not appear in minimal context file", detail)
		}
	}
}

func TestRender_SinglePendingTask_ShowsCount(t *testing.T) {
	tasks := []store.Task{
		{ID: "t1", Title: "Normal task", Status: "pending", Priority: "p2"},
	}
	out := render(nil, tasks)
	if !strings.Contains(out, "1 pending") {
		t.Errorf("expected '1 pending' count, got:\n%s", out)
	}
	// Neither the title nor priority should appear in minimal format.
	if strings.Contains(out, "Normal task") {
		t.Error("task title should not appear in minimal format")
	}
	if strings.Contains(out, "priority:") {
		t.Error("priority should not appear in minimal format")
	}
}

func TestRender_ContainsUpdatedTimestamp(t *testing.T) {
	out := render(nil, nil)
	if !strings.Contains(out, "_Updated:") {
		t.Error("missing updated timestamp")
	}
}

// ── Write + ContextFilePath ───────────────────────────────────────────────────

// TestWrite_CreatesFileAndContent tests that Write successfully creates a context file
// with the expected auto-generated marker. This is a basic smoke test of the write path.
func TestWrite_CreatesFileAndContent(t *testing.T) {
	setupTestEnv(t)

	repoRoot := "/tmp/test-project"
	if err := Write(repoRoot, nil, nil); err != nil {
		t.Fatalf("Write failed: %v", err)
	}

	path, err := ContextFilePath(repoRoot)
	if err != nil {
		t.Fatalf("ContextFilePath failed: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("file not found at %s: %v", path, err)
	}
	if !strings.Contains(string(data), "Auto-generated by Synapses daemon") {
		t.Error("file missing expected content")
	}
}

// TestWrite_AtomicNoPanicOnDoubleWrite tests that Write is idempotent and atomic:
// writing the same context file multiple times should not error, and intermediate
// states with partial writes should not be observable by readers.
func TestWrite_AtomicNoPanicOnDoubleWrite(t *testing.T) {
	setupTestEnv(t)

	repoRoot := "/tmp/test-project-atomic"
	for i := 0; i < 3; i++ {
		if err := Write(repoRoot, nil, nil); err != nil {
			t.Fatalf("Write #%d failed: %v", i, err)
		}
	}
}

// TestContextFilePath_IsInsideSynapsesContext verifies that context files are created
// in the correct location: ~/.synapses/context/<hash>.md
func TestContextFilePath_IsInsideSynapsesContext(t *testing.T) {
	tmp := setupTestEnv(t)

	path, err := ContextFilePath("/some/project")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	expected := filepath.Join(tmp, ".synapses", "context")
	if !strings.HasPrefix(path, expected) {
		t.Errorf("expected path under %s, got %s", expected, path)
	}
	if !strings.HasSuffix(path, ".md") {
		t.Errorf("expected .md suffix, got %s", path)
	}
}

// TestContextFilePath_DifferentProjectsDifferentFiles verifies that different projects
// get different context files, using hash-based filenames.
func TestContextFilePath_DifferentProjectsDifferentFiles(t *testing.T) {
	setupTestEnv(t)

	p1, _ := ContextFilePath("/project/alpha")
	p2, _ := ContextFilePath("/project/beta")
	if p1 == p2 {
		t.Errorf("different projects produced same context file path: %s", p1)
	}
}

// TestContextFilePath_SameProjectSamePath verifies that the function is deterministic:
// calling it with the same project path always returns the same file path.
func TestContextFilePath_SameProjectSamePath(t *testing.T) {
	setupTestEnv(t)

	p1, _ := ContextFilePath("/project/gamma")
	p2, _ := ContextFilePath("/project/gamma")
	if p1 != p2 {
		t.Errorf("same project produced different paths: %s vs %s", p1, p2)
	}
}

// ── Error cases ────────────────────────────────────────────────────────────────

func TestContextFilePath_HomeDir_Error(t *testing.T) {
	// Simulate no HOME (will cause os.UserHomeDir to fail)
	t.Setenv("HOME", "")
	// We can't easily mock UserHomeDir, but we can test with invalid HOME env
	// This test documents the error case exists even if coverage is tricky
	_, err := ContextFilePath("/any/repo")
	// Either succeeds (if HOME fallback exists) or errors — both are valid
	_ = err
}

func TestRender_OnlyInProgressTasks(t *testing.T) {
	tasks := []store.Task{
		{ID: "t1", Status: "in_progress"},
		{ID: "t2", Status: "in_progress"},
	}
	out := render(nil, tasks)
	if !strings.Contains(out, "2 in progress") {
		t.Errorf("expected '2 in progress', got:\n%s", out)
	}
	if strings.Contains(out, "pending") && !strings.Contains(out, "2 in progress") {
		t.Errorf("should not mention pending if there are zero, got:\n%s", out)
	}
}

func TestRender_ZeroTasksButTaskArray(t *testing.T) {
	out := render(nil, []store.Task{})
	// Empty task array means no tasks section
	if strings.Contains(out, "**Tasks**:") {
		t.Errorf("should not show Tasks section for empty array, got:\n%s", out)
	}
}

func TestRender_IdentityWithoutToolGuidance(t *testing.T) {
	id := &graph.ProjectIdentity{
		RepoID: "test",
		Scale:  graph.ScaleSmall,
		Summary: graph.GraphSummary{
			Files:     10,
			Functions: 50,
			Edges:     100,
		},
		// ToolGuidance is empty
	}
	out := render(id, nil)
	if !strings.Contains(out, "# Synapses — test") {
		t.Error("missing project header")
	}
	// Should not include empty guidance block
	if strings.HasPrefix(out, "> \n") {
		t.Error("should not include empty guidance block")
	}
}

// --- Additional coverage tests for error paths and integration ---

// setupTestEnv creates a temporary directory for testing and sets HOME to it.
// Returns the temp directory path. Caller should ensure cleanup via t.Cleanup or defer.
func setupTestEnv(t *testing.T) string {
	tmp := t.TempDir()
	t.Setenv("HOME", tmp)
	return tmp
}

// TestWrite_WithIdentityAndTasks tests Write with full project identity and task list.
// Verifies that the rendered output includes all key information (repo ID, scale, task counts).
func TestWrite_WithIdentityAndTasks(t *testing.T) {
	setupTestEnv(t)

	id := &graph.ProjectIdentity{
		RepoID: "test-repo",
		Scale:  graph.ScaleMedium,
		Summary: graph.GraphSummary{
			Files:     30,
			Functions: 150,
			Edges:     500,
		},
		ToolGuidance: "Use Synapses tools here.",
	}
	tasks := []store.Task{
		{ID: "t1", Title: "Task 1", Status: "pending"},
		{ID: "t2", Title: "Task 2", Status: "in_progress"},
	}

	if err := Write("/test/project", id, tasks); err != nil {
		t.Fatalf("Write with identity and tasks failed: %v", err)
	}

	path, _ := ContextFilePath("/test/project")
	data, _ := os.ReadFile(path)
	content := string(data)

	// Integration check: all components rendered correctly
	if !strings.Contains(content, "test-repo") {
		t.Error("missing repo ID in output")
	}
	if !strings.Contains(content, "medium") {
		t.Error("missing scale in output")
	}
	if !strings.Contains(content, "1 pending") {
		t.Error("missing pending count")
	}
	if !strings.Contains(content, "1 in progress") {
		t.Error("missing in-progress count")
	}
}

// TestContextFilePath_CreatesDirectoryIfMissing tests that ContextFilePath creates
// the ~/.synapses/context directory if it doesn't exist. This is important for
// first-run scenarios where the user has never run Synapses before.
func TestContextFilePath_CreatesDirectoryIfMissing(t *testing.T) {
	tmp := setupTestEnv(t)

	path, err := ContextFilePath("/test/project")
	if err != nil {
		t.Fatalf("ContextFilePath failed: %v", err)
	}

	// Verify directory structure was created
	dir := filepath.Dir(path)
	if _, err := os.Stat(dir); err != nil {
		t.Fatalf("context directory not created: %v", err)
	}

	// Verify it's in the expected location
	expectedDir := filepath.Join(tmp, ".synapses", "context")
	if dir != expectedDir {
		t.Errorf("directory created in wrong location: got %s, want %s", dir, expectedDir)
	}
}

// TestContextFilePath_DirectoryAlreadyExists tests that ContextFilePath is idempotent:
// calling it multiple times should not error even if the directory already exists.
// This is important for reliable long-running daemons that write context files repeatedly.
func TestContextFilePath_DirectoryAlreadyExists(t *testing.T) {
	setupTestEnv(t)

	// Call once to create directory
	path1, _ := ContextFilePath("/proj1")

	// Call again with different project — should not fail even if dir exists
	path2, err := ContextFilePath("/proj2")
	if err != nil {
		t.Fatalf("second ContextFilePath call failed: %v", err)
	}

	if path1 == path2 {
		t.Error("expected different paths for different projects")
	}

	// Both files should be in same directory
	if filepath.Dir(path1) != filepath.Dir(path2) {
		t.Error("expected both paths in same directory")
	}
}

func TestRender_AllTaskStatusesInProgress(t *testing.T) {
	tasks := []store.Task{
		{ID: "t1", Status: "in_progress"},
		{ID: "t2", Status: "in_progress"},
		{ID: "t3", Status: "in_progress"},
	}
	out := render(nil, tasks)
	if !strings.Contains(out, "3 in progress") {
		t.Errorf("expected '3 in progress', got:\n%s", out)
	}
	// Should not show pending count if there are no pending tasks
	if strings.Contains(out, "pending") {
		parts := strings.Split(out, "\n")
		for _, part := range parts {
			if strings.Contains(part, "pending") && strings.Contains(part, "**Tasks**") {
				t.Errorf("should not mention 'pending' when no pending tasks exist")
			}
		}
	}
}

func TestRender_OnlyPendingTasks(t *testing.T) {
	tasks := []store.Task{
		{ID: "t1", Status: "pending"},
		{ID: "t2", Status: "pending"},
	}
	out := render(nil, tasks)
	if !strings.Contains(out, "2 pending") {
		t.Errorf("expected '2 pending', got:\n%s", out)
	}
	// Should not show in_progress if there are no in_progress tasks
	if strings.Contains(out, "in progress") {
		parts := strings.Split(out, "\n")
		for _, part := range parts {
			if strings.Contains(part, "in progress") && strings.Contains(part, "**Tasks**") {
				t.Errorf("should not mention 'in progress' when no in_progress tasks exist")
			}
		}
	}
}

func TestFnvHash_EmptyString(t *testing.T) {
	h := fnvHash("")
	if len(h) != 16 {
		t.Errorf("fnvHash(\"\") length = %d, want 16", len(h))
	}
	// Hash of empty string should be consistent
	h2 := fnvHash("")
	if h != h2 {
		t.Errorf("fnvHash(\"\") not deterministic: %q vs %q", h, h2)
	}
}

func TestFnvHash_SingleCharacter(t *testing.T) {
	h1 := fnvHash("a")
	h2 := fnvHash("b")
	if h1 == h2 {
		t.Errorf("single char hashes collision: %q == %q", h1, h2)
	}
	if len(h1) != 16 || len(h2) != 16 {
		t.Errorf("hash format incorrect: %q, %q", h1, h2)
	}
}

func TestFilterPending_OnlyInProgress(t *testing.T) {
	tasks := []store.Task{
		{ID: "t1", Status: "in_progress"},
		{ID: "t2", Status: "in_progress"},
	}
	got := filterPending(tasks)
	if len(got) != 2 {
		t.Errorf("expected 2 in_progress tasks, got %d", len(got))
	}
	for _, task := range got {
		if task.Status != "in_progress" {
			t.Errorf("expected in_progress, got %q", task.Status)
		}
	}
}

func TestWrite_RelativePathHandling(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("HOME", tmp)

	// Test with relative path
	if err := Write("./relative/path", nil, nil); err != nil {
		t.Fatalf("Write with relative path failed: %v", err)
	}

	path, _ := ContextFilePath("./relative/path")
	if _, err := os.Stat(path); err != nil {
		t.Errorf("file not created for relative path: %v", err)
	}
}

func TestWrite_ContextFilePathError(t *testing.T) {
	// If ContextFilePath returns an error (e.g., HOME not accessible),
	// Write should propagate that error
	if err := Write("", nil, nil); err == nil {
		// Empty repoRoot may or may not error depending on hash behavior
		// Just verify Write handles the call without panicking
	}
}

func TestWrite_WriteFileError(t *testing.T) {
	// Write uses an atomic write: it creates a .tmp file first, then renames it.
	// If the context directory is read-only, os.WriteFile will fail.
	// Write must propagate that error rather than silently swallowing it.
	//
	// Setup: create the ~/.synapses/context dir, then chmod it read-only
	// so the .tmp write fails.
	tmpHome := t.TempDir()
	t.Setenv("HOME", tmpHome)

	// Pre-create the directory so ContextFilePath succeeds.
	contextDir := filepath.Join(tmpHome, ".synapses", "context")
	if err := os.MkdirAll(contextDir, 0o755); err != nil {
		t.Fatalf("setup: create context dir: %v", err)
	}
	// Make it read-only — subsequent writes into this dir must fail.
	if err := os.Chmod(contextDir, 0o444); err != nil {
		t.Fatalf("setup: chmod read-only: %v", err)
	}
	t.Cleanup(func() {
		// Restore write permission so TempDir cleanup succeeds.
		_ = os.Chmod(contextDir, 0o755)
	})

	err := Write("/some/project", nil, nil)
	if err == nil {
		t.Error("Write into a read-only directory should return an error")
	}
}

func TestContextFilePath_MkdirAllError(t *testing.T) {
	// If HOME points to a regular file (not a directory), os.MkdirAll will fail
	// when it tries to create the ~/.synapses/context/ sub-path.
	// ContextFilePath must return that error rather than panic.
	tmpDir := t.TempDir()
	fileAsHome := filepath.Join(tmpDir, "not-a-dir")
	if err := os.WriteFile(fileAsHome, []byte("I am a file"), 0o644); err != nil {
		t.Fatalf("setup: create fake HOME file: %v", err)
	}
	t.Setenv("HOME", fileAsHome)

	_, err := ContextFilePath("/project/root")
	if err == nil {
		t.Error("ContextFilePath should error when HOME is a file (MkdirAll fails)")
	}
}

func TestRender_WithIdentityAndGuidance(t *testing.T) {
	id := &graph.ProjectIdentity{
		RepoID:       "my-app",
		Scale:        graph.ScaleLarge,
		ToolGuidance: "Large repo — always use Synapses tools.",
		Summary: graph.GraphSummary{
			Files:     500,
			Functions: 2000,
			Edges:     8000,
		},
	}
	out := render(id, nil)

	// Verify all components are present
	if !strings.Contains(out, "my-app") {
		t.Error("missing repo ID")
	}
	if !strings.Contains(out, "Large repo") {
		t.Error("missing tool guidance content")
	}
	if !strings.Contains(out, "large") {
		t.Error("missing scale indicator")
	}
	if !strings.Contains(out, "500") || !strings.Contains(out, "2000") || !strings.Contains(out, "8000") {
		t.Error("missing summary statistics")
	}
}

func TestRender_MixedTaskStatuses(t *testing.T) {
	tasks := []store.Task{
		{ID: "p1", Status: "pending"},
		{ID: "p2", Status: "pending"},
		{ID: "i1", Status: "in_progress"},
		{ID: "d1", Status: "done"},
		{ID: "c1", Status: "cancelled"},
	}
	out := render(nil, tasks)

	// Should show 2 pending and 1 in progress
	if !strings.Contains(out, "2 pending") {
		t.Errorf("expected '2 pending', got:\n%s", out)
	}
	if !strings.Contains(out, "1 in progress") {
		t.Errorf("expected '1 in progress', got:\n%s", out)
	}
	// Should not mention done or cancelled in task summary
	if strings.Count(out, "done") > 0 {
		// done might appear in the timestamp or elsewhere, just count
		if strings.Count(out, "done") > 1 { // allow for "done" in the file timestamp
			t.Error("'done' should not appear in task summary")
		}
	}
}

func TestFnvHash_LongPath(t *testing.T) {
	longPath := "/very/long/path/to/some/project/with/many/segments/that/goes/on/and/on/and/on/and/on"
	h := fnvHash(longPath)
	if len(h) != 16 {
		t.Errorf("expected 16-char hash for long path, got %d: %s", len(h), h)
	}
	// Should be deterministic
	h2 := fnvHash(longPath)
	if h != h2 {
		t.Errorf("hash not deterministic for long path: %s vs %s", h, h2)
	}
}

func TestFilterPending_MixedStatuses(t *testing.T) {
	tasks := []store.Task{
		{ID: "1", Status: "pending"},
		{ID: "2", Status: "in_progress"},
		{ID: "3", Status: "pending"},
		{ID: "4", Status: "done"},
		{ID: "5", Status: "in_progress"},
	}
	got := filterPending(tasks)
	if len(got) != 4 { // 2 pending + 2 in_progress
		t.Fatalf("expected 4 pending/in_progress, got %d", len(got))
	}
	// Verify order is preserved (first 2 pending, then 2 in_progress)
	if got[0].ID != "1" || got[1].ID != "2" || got[2].ID != "3" || got[3].ID != "5" {
		t.Errorf("unexpected order: %v", got)
	}
}

func TestWrite_RenameError(t *testing.T) {
	// Test the atomic write rename error path.
	// We write successfully but then fail the rename.
	// This exercises the os.Rename error handling in Write.
	tmpHome := t.TempDir()
	t.Setenv("HOME", tmpHome)

	// Pre-create the context directory with write permissions
	contextDir := filepath.Join(tmpHome, ".synapses", "context")
	if err := os.MkdirAll(contextDir, 0o755); err != nil {
		t.Fatalf("setup: create context dir: %v", err)
	}

	// Write successfully first
	if err := Write("/test/project/1", nil, nil); err != nil {
		t.Fatalf("initial Write failed: %v", err)
	}

	// Now make the directory read-only to prevent the rename
	if err := os.Chmod(contextDir, 0o555); err != nil {
		t.Fatalf("setup: chmod read-only: %v", err)
	}
	t.Cleanup(func() {
		// Restore write permission so TempDir cleanup succeeds
		_ = os.Chmod(contextDir, 0o755)
	})

	// Try to write again with a different project (will create new .tmp file)
	// The rename should fail due to read-only directory
	err := Write("/test/project/2", nil, nil)
	if err == nil {
		// On some systems, this might not fail as expected
		// (e.g., if the user is root), so we don't strictly fail the test
		// but we document the expected behavior
		t.Log("Note: rename error test may not fail on all systems (e.g., running as root)")
	}
}
