package peer

import (
	"bytes"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/SynapsesOS/synapses/internal/config"
	"github.com/SynapsesOS/synapses/internal/graph"
	"github.com/SynapsesOS/synapses/internal/store"
)

// PeerStatus is the last-known health and metadata of a configured peer.
type PeerStatus struct {
	Name        string    `json:"name"`
	URL         string    `json:"url"`
	Connected   bool      `json:"connected"`
	Healthy     bool      `json:"healthy"`
	TrustLevel  string    `json:"trust_level"`
	NodeCount   int       `json:"node_count,omitempty"`
	SharedCount int       `json:"shared_count,omitempty"` // entities shared with local graph
	LastSeenAt  time.Time `json:"last_seen_at,omitempty"`
	Error       string    `json:"error,omitempty"`
}

// PeerClient is an HTTP client for a single configured peer.
type PeerClient struct {
	cfg     config.PeerConfig
	httpCli *http.Client
}

// NewPeerClient creates a PeerClient for the given peer config. It uses a
// permissive TLS config that accepts self-signed certificates (peer certs are
// generated by ensureSelfSignedCert and are not CA-signed).
func NewPeerClient(cfg config.PeerConfig) *PeerClient {
	transport := &http.Transport{
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: strings.HasPrefix(cfg.URL, "https://localhost") ||
				strings.HasPrefix(cfg.URL, "https://127."),
		},
		ResponseHeaderTimeout: 10 * time.Second,
	}
	return &PeerClient{
		cfg: cfg,
		httpCli: &http.Client{
			Transport: transport,
			Timeout:   15 * time.Second,
		},
	}
}

// Ping fetches the peer's identity card (no auth required).
func (pc *PeerClient) Ping() (*IdentityResponse, error) {
	resp, err := pc.httpCli.Get(pc.cfg.URL + "/api/v1/identity")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	var id IdentityResponse
	if err := json.NewDecoder(resp.Body).Decode(&id); err != nil {
		return nil, fmt.Errorf("decode identity: %w", err)
	}
	return &id, nil
}

// FetchDigest returns the peer's exported API digest.
func (pc *PeerClient) FetchDigest() ([]DigestEntry, error) {
	req, err := pc.newRequest(http.MethodGet, "/api/v1/api-digest", nil)
	if err != nil {
		return nil, err
	}
	resp, err := pc.httpCli.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("peer returned %d", resp.StatusCode)
	}
	var entries []DigestEntry
	if err := json.NewDecoder(resp.Body).Decode(&entries); err != nil {
		return nil, fmt.Errorf("decode digest: %w", err)
	}
	return entries, nil
}

// QueryEntity carves a subgraph for entity from the peer project.
func (pc *PeerClient) QueryEntity(name string, depth int) (*graph.SubGraph, error) {
	body, _ := json.Marshal(QueryRequest{Entity: name, Depth: depth})
	req, err := pc.newRequest(http.MethodPost, "/api/v1/query", bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := pc.httpCli.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusNotFound {
		return nil, fmt.Errorf("entity %q not found in peer", name)
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("peer returned %d", resp.StatusCode)
	}
	var sub graph.SubGraph
	if err := json.NewDecoder(resp.Body).Decode(&sub); err != nil {
		return nil, fmt.Errorf("decode subgraph: %w", err)
	}
	return &sub, nil
}

// FetchClaims returns the peer's active work claims.
func (pc *PeerClient) FetchClaims() ([]store.WorkClaim, error) {
	req, err := pc.newRequest(http.MethodGet, "/api/v1/claims", nil)
	if err != nil {
		return nil, err
	}
	resp, err := pc.httpCli.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("peer returned %d", resp.StatusCode)
	}
	var claims []store.WorkClaim
	if err := json.NewDecoder(resp.Body).Decode(&claims); err != nil {
		return nil, fmt.Errorf("decode claims: %w", err)
	}
	return claims, nil
}

// FetchAgents returns the active agents on this peer (seen in the last 15 min).
// Used by the health monitor to sync remote agent presence into the local store.
func (pc *PeerClient) FetchAgents() ([]store.AgentSummary, error) {
	req, err := pc.newRequest(http.MethodGet, "/api/v1/agents", nil)
	if err != nil {
		return nil, err
	}
	resp, err := pc.httpCli.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("peer returned %d", resp.StatusCode)
	}
	var agents []store.AgentSummary
	if err := json.NewDecoder(resp.Body).Decode(&agents); err != nil {
		return nil, fmt.Errorf("decode agents: %w", err)
	}
	return agents, nil
}

// BroadcastIntent sends an intent notification to this peer. Errors are
// intentionally ignored by callers (fire-and-forget).
func (pc *PeerClient) BroadcastIntent(msg IntentMessage) error {
	body, _ := json.Marshal(msg)
	req, err := pc.newRequest(http.MethodPost, "/api/v1/intents", bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := pc.httpCli.Do(req)
	if err != nil {
		return err
	}
	resp.Body.Close()
	return nil
}

// Name returns the configured peer name.
func (pc *PeerClient) Name() string { return pc.cfg.Name }

// newRequest creates a request with the peer's bearer token pre-applied.
func (pc *PeerClient) newRequest(method, path string, body *bytes.Reader) (*http.Request, error) {
	var req *http.Request
	var err error
	if body != nil {
		req, err = http.NewRequest(method, pc.cfg.URL+path, body)
	} else {
		req, err = http.NewRequest(method, pc.cfg.URL+path, nil)
	}
	if err != nil {
		return nil, err
	}
	if pc.cfg.Token != "" {
		req.Header.Set("Authorization", "Bearer "+pc.cfg.Token)
	}
	return req, nil
}
