package parser

import (
	"bytes"
	"path/filepath"
	"strings"

	"github.com/SynapsesOS/synapses/internal/graph"
)

// DetectProvenance derives the provenance tier for a file from its path and
// the first 512 bytes of content. Runs at index time with no LLM or I/O beyond
// what the parser has already read.
//
// Priority order:
//  1. Vendored  — path contains vendor/, node_modules/, third_party/
//  2. Generated — file name matches codegen suffixes, OR file starts with a
//     well-known codegen header comment
//  3. UserAuthored — everything else (the safe default)
func DetectProvenance(path string, src []byte) graph.ProvenanceType {
	// Normalise to forward slashes for cross-platform path matching.
	rel := filepath.ToSlash(path)

	// 1. Vendored: path-segment check (must be a full segment, not a substring).
	// Also check HasPrefix for relative paths like "vendor/..." that lack the
	// leading slash (common when Synapses is given relative file paths).
	for _, seg := range []string{"/vendor/", "/node_modules/", "/third_party/", "/_vendor/"} {
		if strings.Contains(rel, seg) || strings.HasPrefix(rel, seg[1:]) {
			return graph.ProvenanceVendored
		}
	}

	// 1.5. Generated: compiled/bundled output directory check.
	// Files under these well-known frontend build output directories are always
	// compiler/bundler artefacts — they should never influence architectural rules.
	for _, seg := range []string{"/dist/", "/.next/", "/.nuxt/", "/.svelte-kit/"} {
		if strings.Contains(rel, seg) || strings.HasPrefix(rel, seg[1:]) {
			return graph.ProvenanceGenerated
		}
	}

	// 2. Generated: file-name pattern check.
	base := filepath.Base(path)
	if isGeneratedFilename(base) {
		return graph.ProvenanceGenerated
	}

	// 3. Generated: content-header check (first 512 bytes is sufficient).
	head := src
	if len(head) > 512 {
		head = head[:512]
	}
	for _, marker := range codegenHeaders {
		if bytes.Contains(head, marker) {
			return graph.ProvenanceGenerated
		}
	}

	return graph.ProvenanceUserAuthored
}

// isGeneratedFilename returns true for file base names that match well-known
// code-generation output patterns.
func isGeneratedFilename(base string) bool {
	return strings.HasSuffix(base, ".pb.go") ||
		strings.HasSuffix(base, "_generated.go") ||
		strings.HasSuffix(base, ".gen.go") ||
		strings.HasSuffix(base, ".generated.go") ||
		strings.HasSuffix(base, "_mock.go") ||
		strings.HasSuffix(base, ".mock.go") ||
		strings.HasPrefix(base, "zz_generated") ||
		strings.HasPrefix(base, "mock_") && strings.HasSuffix(base, ".go") ||
		// Python generated
		strings.HasSuffix(base, "_pb2.py") ||
		strings.HasSuffix(base, "_pb2_grpc.py")
}

// codegenHeaders is the list of byte patterns that appear in the first few lines
// of auto-generated source files across multiple languages.
var codegenHeaders = [][]byte{
	[]byte("// Code generated"),
	[]byte("// DO NOT EDIT"),
	[]byte("/* Code generated"),
	[]byte("/* DO NOT EDIT"),
	[]byte("# Code generated"),
	[]byte("# DO NOT EDIT"),
	[]byte("# This file is automatically generated"),
	[]byte("// This file is automatically generated"),
	[]byte("// Generated by"),
	[]byte("// Automatically generated"),
	[]byte("// AUTO-GENERATED"),
	[]byte("// autogenerated"),
}

// ApplyProvenance sets the Provenance field on all nodes belonging to path.
// Called by WalkDir/IncrementalReindex/ParseFile immediately after a successful
// parse so that every node carries its trust tier from the moment it enters the graph.
// Nodes in user-authored files are left unchanged (ProvenanceUserAuthored is the zero value).
func ApplyProvenance(g *graph.Graph, path string, src []byte) {
	p := DetectProvenance(path, src)
	if p == graph.ProvenanceUserAuthored {
		return // nothing to set — default is already correct
	}
	// Use the write-locked setter to avoid a data race: FindByFile returns
	// *Node pointers after releasing its read lock, and mutating them without
	// re-acquiring the write lock is a race with concurrent BFS reads.
	g.SetFileProvenance(path, p)
}
