package parser

import (
	"testing"

	"github.com/SynapsesOS/synapses/internal/graph"
)

func TestDetectProvenance_UserAuthored(t *testing.T) {
	p := DetectProvenance("src/api/handler.go", []byte("package api"))
	if p != graph.ProvenanceUserAuthored {
		t.Errorf("want user-authored, got %q", p)
	}
}

func TestDetectProvenance_Vendored(t *testing.T) {
	cases := []string{
		"vendor/github.com/gin-gonic/gin/gin.go",
		"node_modules/express/index.js",
		"third_party/protobuf/descriptor.go",
	}
	for _, path := range cases {
		p := DetectProvenance(path, nil)
		if p != graph.ProvenanceVendored {
			t.Errorf("%q: want vendored, got %q", path, p)
		}
	}
}

func TestDetectProvenance_GeneratedFilename(t *testing.T) {
	cases := []string{
		"api/user.pb.go",
		"internal/zz_generated.deepcopy.go",
		"mocks/mock_store.go",
		"gen/schema.gen.go",
		"pb/service_pb2.py",
	}
	for _, path := range cases {
		p := DetectProvenance(path, nil)
		if p != graph.ProvenanceGenerated {
			t.Errorf("%q: want generated, got %q", path, p)
		}
	}
}

func TestDetectProvenance_GeneratedHeader(t *testing.T) {
	cases := [][]byte{
		[]byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb"),
		[]byte("// DO NOT EDIT\npackage main"),
		[]byte("# This file is automatically generated\nfrom django.db import models"),
		[]byte("// AUTO-GENERATED FILE - do not modify manually"),
	}
	for _, src := range cases {
		p := DetectProvenance("any/file.go", src)
		if p != graph.ProvenanceGenerated {
			t.Errorf("src %q: want generated, got %q", src[:30], p)
		}
	}
}

func TestDetectProvenance_OutputDirs(t *testing.T) {
	// Files under known output dirs must be detected as generated —
	// both absolute-style paths (/project/dist/...) and relative (dist/...).
	cases := []string{
		"frontend/dist/bundle.js",
		"app/.next/server/pages/index.js",
		"app/.nuxt/components/app.vue",
		"app/.svelte-kit/output/index.js",
		"app/dist/types/api.d.ts",
		// Relative paths without a leading component before the output dir:
		"dist/bundle.js",
		".next/server/pages/index.js",
	}
	for _, path := range cases {
		p := DetectProvenance(path, nil)
		if p != graph.ProvenanceGenerated {
			t.Errorf("%q: want generated, got %q", path, p)
		}
	}
}

func TestDetectProvenance_HandwrittenDTS(t *testing.T) {
	// .d.ts under src/ is user-authored (not in output dir).
	p := DetectProvenance("src/types/api.d.ts", []byte("export interface User {}"))
	if p != graph.ProvenanceUserAuthored {
		t.Errorf("hand-written .d.ts: want user-authored, got %q", p)
	}
}
