package store

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
	"time"
)

// MemorySearchResult represents a memory matched by vector similarity search.
type MemorySearchResult struct {
	MemoryID       string  `json:"memory_id"`
	Content        string  `json:"content"`
	Tier           string  `json:"tier"`
	EntityID       string  `json:"entity_id,omitempty"`
	Score          float64 `json:"score"`                     // cosine similarity, higher = more relevant
	StaleEmbedding bool    `json:"stale_embedding,omitempty"` // true when anchored entity changed since embedding was computed
}

// memoryContentHash computes an 8-char hex hash of the memory content
// used to detect when a memory's embedding is out of date after content changes.
func memoryContentHash(content string) string {
	sum := sha256.Sum256([]byte(content))
	return hex.EncodeToString(sum[:4]) // 8 hex chars
}

// UpsertMemoryEmbedding stores or replaces the vector embedding for a memory.
// vec is encoded as a little-endian float32 BLOB. model is the model name
// used to generate the embedding (for cache invalidation when the model changes).
// A content_hash of the memory's content is computed and stored so that
// GetMemoriesWithoutEmbeddings can detect stale embeddings when memory content changes.
// Thread-safe: each call is a single UPSERT.
func (s *Store) UpsertMemoryEmbedding(memoryID, model string, vec []float32) error {
	if memoryID == "" {
		return fmt.Errorf("upsert memory embedding: empty memory_id")
	}
	if len(vec) == 0 {
		return fmt.Errorf("upsert memory embedding: empty vector")
	}
	// Pre-normalize to unit length so cosine similarity reduces to a dot product.
	nvec := normalizeVec(vec)
	if nvec == nil {
		return fmt.Errorf("upsert memory embedding: zero-magnitude vector")
	}
	blob := vecToBlob(nvec)

	// Compute content hash for change detection.
	var content string
	_ = s.knowledgeDB.QueryRow(`SELECT content FROM memories WHERE id = ?`, memoryID).
		Scan(&content)
	hash := memoryContentHash(content)

	_, err := s.knowledgeDB.Exec(`
		INSERT INTO memory_embeddings (memory_id, model, embedding, content_hash, stale, embedded_at)
		VALUES (?, ?, ?, ?, 0, ?)
		ON CONFLICT(memory_id) DO UPDATE SET
			model        = excluded.model,
			embedding    = excluded.embedding,
			content_hash = excluded.content_hash,
			stale        = 0,
			embedded_at  = excluded.embedded_at`,
		memoryID, model, blob, hash, time.Now().Unix(),
	)
	if err != nil {
		return fmt.Errorf("upsert memory embedding: %w", err)
	}

	// Update the in-memory HNSW index. Add() replaces existing keys (safe upsert).
	s.hnswAdd(memoryID, nvec)

	return nil
}

// GetMemoryEmbedding returns the stored embedding vector for a memory, or nil
// if the memory has no embedding or the embedding is stale.
func (s *Store) GetMemoryEmbedding(memoryID string) []float32 {
	var blob []byte
	err := s.knowledgeDB.QueryRow(
		`SELECT embedding FROM memory_embeddings WHERE memory_id = ? AND stale = 0`,
		memoryID,
	).Scan(&blob)
	if err != nil {
		return nil
	}
	return blobToVec(blob)
}

// CountEmbeddableMemories returns the total number of non-expired, non-stale memories (P8-10).
// This is the denominator for embedding coverage percentage.
func (s *Store) CountEmbeddableMemories() int {
	now := time.Now().UTC().Format(time.RFC3339)
	var n int
	s.knowledgeDB.QueryRow(`SELECT COUNT(*) FROM memories WHERE expires_at > ? AND stale = 0`, now).Scan(&n)
	return n
}

// InvalidateEmbeddingsByModel marks all memory embeddings generated by a
// different model as stale. This is the migration step for embedding model
// upgrades: when the builtin model changes (e.g., MiniLM → nomic-embed-text),
// old embeddings are in a different vector space and produce meaningless
// similarity scores against new embeddings. Marking them stale forces
// re-embedding on the next EmbedAllMemories pass.
// Returns the number of embeddings invalidated. A no-op when all embeddings
// already match currentModel or the table is empty.
func (s *Store) InvalidateEmbeddingsByModel(currentModel string) (int, error) {
	if currentModel == "" {
		return 0, nil
	}
	result, err := s.knowledgeDB.Exec(
		`UPDATE memory_embeddings SET stale = 1 WHERE model != ? AND model != '' AND stale = 0`,
		currentModel,
	)
	if err != nil {
		return 0, fmt.Errorf("invalidate embeddings by model: %w", err)
	}
	n, _ := result.RowsAffected()
	return int(n), nil
}

// GetMemoriesWithoutEmbeddings returns up to limit memory IDs that need
// (re-)embedding. A memory qualifies if:
//   - it has no embedding row at all (new memory)
//   - its content_hash no longer matches (content changed since embedding)
//   - its embedding is marked stale=1 (model upgrade or anchor invalidation)
//
// Only non-expired, non-stale (memory-level) memories are returned.
// Pass limit=0 to return all matching IDs (no cap).
func (s *Store) GetMemoriesWithoutEmbeddings(limit int) ([]string, error) {
	now := time.Now().UTC().Format(time.RFC3339)

	// BUG-024: Split into two queries to avoid loading all content into Go.
	// Phase 1: find memories with NO embedding at all (pure SQL, no content scan).
	var ids []string
	missingRows, err := s.knowledgeDB.Query(`
		SELECT m.id
		FROM memories m
		LEFT JOIN memory_embeddings e ON m.id = e.memory_id
		WHERE m.expires_at > ?
		  AND m.stale = 0
		  AND e.memory_id IS NULL`, now)
	if err != nil {
		return nil, fmt.Errorf("get memories without embeddings: %w", err)
	}
	for missingRows.Next() {
		var id string
		if err := missingRows.Scan(&id); err != nil {
			missingRows.Close()
			return nil, err
		}
		ids = append(ids, id)
		if limit > 0 && len(ids) >= limit {
			break
		}
	}
	missingRows.Close()
	if err := missingRows.Err(); err != nil {
		return nil, err
	}

	if limit > 0 && len(ids) >= limit {
		return ids, nil
	}

	// Phase 2a: find memories with explicitly stale embeddings (pure SQL, no content load).
	remaining := limit - len(ids)
	if limit == 0 {
		remaining = 0 // 0 means no cap
	}
	staleRows, err := s.knowledgeDB.Query(`
		SELECT e.memory_id
		FROM memory_embeddings e
		JOIN memories m ON m.id = e.memory_id
		WHERE m.expires_at > ?
		  AND m.stale = 0
		  AND e.stale = 1`, now)
	if err == nil {
		for staleRows.Next() {
			var id string
			if staleRows.Scan(&id) == nil {
				ids = append(ids, id)
				if remaining > 0 && len(ids) >= limit {
					break
				}
			}
		}
		staleRows.Close()
	}

	if limit > 0 && len(ids) >= limit {
		return ids, nil
	}

	// Phase 2b: find memories with changed content (requires Go-side hash comparison).
	// Only loads content for memories that HAVE an embedding and are NOT already stale.
	// This is the expensive path but only runs for the content-changed subset.
	changedRows, err := s.knowledgeDB.Query(`
		SELECT m.id, m.content, e.content_hash
		FROM memories m
		JOIN memory_embeddings e ON m.id = e.memory_id
		WHERE m.expires_at > ?
		  AND m.stale = 0
		  AND e.stale = 0`, now)
	if err != nil {
		return ids, nil // fail-open: return what we have
	}
	defer changedRows.Close()

	for changedRows.Next() {
		var id, content, storedHash string
		if err := changedRows.Scan(&id, &content, &storedHash); err != nil {
			continue
		}
		if memoryContentHash(content) != storedHash {
			ids = append(ids, id)
			if limit > 0 && len(ids) >= limit {
				break
			}
		}
	}
	return ids, changedRows.Err()
}

// GetMemoryTextForEmbedding returns the text content that should be embedded
// for a memory. Returns ("", false) if the memory does not exist or is expired/stale.
func (s *Store) GetMemoryTextForEmbedding(memoryID string) (string, bool) {
	now := time.Now().UTC().Format(time.RFC3339)
	var content string
	err := s.knowledgeDB.QueryRow(
		`SELECT content FROM memories WHERE id = ? AND expires_at > ? AND stale = 0`,
		memoryID, now,
	).Scan(&content)
	if err != nil {
		return "", false
	}
	return content, true
}

// MarkMemoryEmbeddingsStale sets stale=1 on embeddings for the given memory IDs.
// This is the foundation for Sprint 10.7 (graph-anchored embedding invalidation):
// when a file watcher detects an entity change, embeddings of memories anchored to
// that entity are marked stale. On next recall(), stale embeddings are re-embedded
// before scoring. Idempotent. A no-op when memoryIDs is empty.
// Processes in batches of 500 to respect SQLite variable limits.
// Also removes stale entries from the HNSW index — stale vectors shouldn't
// participate in ANN search until re-embedded.
func (s *Store) MarkMemoryEmbeddingsStale(memoryIDs []string) error {
	if len(memoryIDs) == 0 {
		return nil
	}

	// Stale embeddings remain in the HNSW index — the search API includes them
	// with a StaleEmbedding flag so callers can surface "possibly outdated" results.
	// They'll be replaced in HNSW when re-embedded (Add is an upsert).

	const batchSize = 500
	for i := 0; i < len(memoryIDs); i += batchSize {
		end := i + batchSize
		if end > len(memoryIDs) {
			end = len(memoryIDs)
		}
		batch := memoryIDs[i:end]
		placeholders := strings.Repeat("?,", len(batch))
		placeholders = placeholders[:len(placeholders)-1]
		args := make([]any, len(batch))
		for j, id := range batch {
			args[j] = id
		}
		if _, err := s.knowledgeDB.Exec(
			`UPDATE memory_embeddings SET stale = 1 WHERE memory_id IN (`+placeholders+`)`,
			args...,
		); err != nil {
			return fmt.Errorf("mark memory embeddings stale: %w", err)
		}
	}
	return nil
}

// GetMemoryIDsByAnchorNodes returns the IDs of non-stale, non-expired memories
// that are anchored to ANY of the given node IDs via the memory_anchors table.
// Used by the file watcher to cheaply find which memory embeddings to invalidate
// after a node changes — we only need IDs, not full Memory structs.
// Processes in batches of 500 to respect SQLite variable limits.
// Returns (nil, nil) when nodeIDs is empty.
func (s *Store) GetMemoryIDsByAnchorNodes(nodeIDs []string, limit int) ([]string, error) {
	if len(nodeIDs) == 0 || limit <= 0 {
		return nil, nil
	}
	now := time.Now().UTC().Format(time.RFC3339)
	seen := make(map[string]struct{})
	var result []string

	const batchSize = 500
	for i := 0; i < len(nodeIDs) && len(result) < limit; i += batchSize {
		end := i + batchSize
		if end > len(nodeIDs) {
			end = len(nodeIDs)
		}
		batch := nodeIDs[i:end]
		placeholders := strings.Repeat("?,", len(batch))
		placeholders = placeholders[:len(placeholders)-1]
		args := make([]any, 0, len(batch)+1)
		for _, id := range batch {
			args = append(args, id)
		}
		args = append(args, now)
		rows, err := s.knowledgeDB.Query(`
			SELECT DISTINCT ma.memory_id
			FROM memory_anchors ma
			JOIN memories m ON ma.memory_id = m.id
			WHERE ma.node_id IN (`+placeholders+`)
			  AND m.stale = 0
			  AND m.expires_at > ?`, args...)
		if err != nil {
			return nil, fmt.Errorf("get memory ids by anchor nodes: %w", err)
		}
		for rows.Next() {
			var id string
			if err := rows.Scan(&id); err != nil {
				rows.Close()
				return nil, fmt.Errorf("scan anchor memory id: %w", err)
			}
			if _, ok := seen[id]; !ok {
				seen[id] = struct{}{}
				result = append(result, id)
				if len(result) >= limit {
					break
				}
			}
		}
		if err := rows.Err(); err != nil {
			rows.Close()
			return nil, err
		}
		rows.Close()
	}
	return result, nil
}

// GetStaleEmbeddingMemoryIDs returns memory IDs whose embeddings are stale
// (stale=1 in memory_embeddings) but whose memory records are still valid
// (non-stale, non-expired). Up to limit IDs are returned.
// Used by the semantic recall channel to drive lazy re-embedding: stale
// embeddings are refreshed just before the vector search runs so they
// participate in scoring instead of being silently excluded.
func (s *Store) GetStaleEmbeddingMemoryIDs(limit int) ([]string, error) {
	if limit <= 0 {
		limit = 50
	}
	now := time.Now().UTC().Format(time.RFC3339)
	rows, err := s.knowledgeDB.Query(`
		SELECT me.memory_id
		FROM memory_embeddings me
		JOIN memories m ON me.memory_id = m.id
		WHERE me.stale = 1
		  AND m.stale = 0
		  AND m.expires_at > ?
		ORDER BY me.embedded_at DESC
		LIMIT ?`, now, limit)
	if err != nil {
		return nil, fmt.Errorf("get stale embedding memory ids: %w", err)
	}
	defer rows.Close()

	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, fmt.Errorf("scan stale embedding id: %w", err)
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

// DeleteMemoryEmbeddings removes embeddings for the given memory IDs.
// Called during memory expiry cleanup. A no-op when memoryIDs is empty.
// Processes in batches of 500 to respect SQLite variable limits.
// Also removes the corresponding entries from the in-memory HNSW index.
func (s *Store) DeleteMemoryEmbeddings(memoryIDs []string) error {
	if len(memoryIDs) == 0 {
		return nil
	}

	// Remove from HNSW index first (before SQLite delete).
	s.hnswDeleteBatch(memoryIDs)

	const batchSize = 500
	for i := 0; i < len(memoryIDs); i += batchSize {
		end := i + batchSize
		if end > len(memoryIDs) {
			end = len(memoryIDs)
		}
		batch := memoryIDs[i:end]
		placeholders := strings.Repeat("?,", len(batch))
		placeholders = placeholders[:len(placeholders)-1]
		args := make([]any, len(batch))
		for j, id := range batch {
			args[j] = id
		}
		if _, err := s.knowledgeDB.Exec(
			`DELETE FROM memory_embeddings WHERE memory_id IN (`+placeholders+`)`,
			args...,
		); err != nil {
			return fmt.Errorf("delete memory embeddings: %w", err)
		}
	}
	return nil
}

// memoryVectorSearchBruteForce is the O(N) fallback path for memory vector search.
// Routes through the context-aware variant with context.Background() and no threshold.
func (s *Store) memoryVectorSearchBruteForce(normQuery []float32, limit int) ([]MemorySearchResult, error) {
	return s.memoryVectorSearchBruteForceWithThresholdCtx(context.Background(), normQuery, limit, 0)
}

// MemoryVectorSearchWithThreshold performs cosine similarity search with a
// minimum similarity threshold. Results below the threshold are excluded.
// Useful for recall() where low-confidence matches should not pollute results.
//
// Uses HNSW fast path when available, with threshold applied post-search.
// Falls back to brute-force scan when HNSW index is not ready.
func (s *Store) MemoryVectorSearchWithThreshold(queryVec []float32, limit int, minScore float64) ([]MemorySearchResult, error) {
	return s.MemoryVectorSearchWithThresholdCtx(context.Background(), queryVec, limit, minScore)
}

// MemoryVectorSearchWithThresholdCtx is the context-aware variant of MemoryVectorSearchWithThreshold.
func (s *Store) MemoryVectorSearchWithThresholdCtx(ctx context.Context, queryVec []float32, limit int, minScore float64) ([]MemorySearchResult, error) {
	if limit <= 0 {
		limit = 20
	}
	if len(queryVec) == 0 {
		return nil, nil
	}

	// Pre-normalize query vector so dot product = cosine similarity.
	normQuery := normalizeVec(queryVec)
	if normQuery == nil {
		return nil, nil
	}

	threshold := float32(minScore)

	// Fast path: HNSW ANN index with threshold filter.
	if s.memoryHNSWReady() {
		candidates := s.hnswSearch(normQuery, limit)
		if len(candidates) > 0 {
			h := &topKHeap{k: limit}
			for _, c := range candidates {
				if c.score < threshold {
					continue
				}
				h.tryPush(c.id, c.score, false)
			}
			winners := h.drain()
			if len(winners) > 0 {
				return s.fetchMemorySearchResultsCtx(ctx, winners)
			}
		}
	}

	// Fallback: brute-force scan with threshold.
	return s.memoryVectorSearchBruteForceWithThresholdCtx(ctx, normQuery, limit, threshold)
}

// memoryVectorSearchBruteForceWithThreshold is the O(N) fallback with threshold.
func (s *Store) memoryVectorSearchBruteForceWithThreshold(normQuery []float32, limit int, threshold float32) ([]MemorySearchResult, error) {
	return s.memoryVectorSearchBruteForceWithThresholdCtx(context.Background(), normQuery, limit, threshold)
}

// memoryVectorSearchBruteForceWithThresholdCtx is the context-aware variant of memoryVectorSearchBruteForceWithThreshold.
// Concurrency is bounded by s.bfSemaphore to prevent GC pressure under load.
func (s *Store) memoryVectorSearchBruteForceWithThresholdCtx(ctx context.Context, normQuery []float32, limit int, threshold float32) ([]MemorySearchResult, error) {
	if s.bfSemaphore != nil {
		select {
		case s.bfSemaphore <- struct{}{}:
			defer func() { <-s.bfSemaphore }()
		case <-ctx.Done():
			return nil, ctx.Err()
		}
	}
	now := time.Now().UTC().Format(time.RFC3339)
	rows, err := s.knowledgeDB.QueryContext(ctx, `
		SELECT e.memory_id, e.embedding, e.stale
		FROM memory_embeddings e
		JOIN memories m ON e.memory_id = m.id
		WHERE m.stale = 0
		  AND m.expires_at > ?
		ORDER BY e.rowid DESC
		LIMIT 50000`, now)
	if err != nil {
		return nil, fmt.Errorf("memory vector search with threshold (brute-force): %w", err)
	}
	defer rows.Close()

	h := &topKHeap{k: limit}
	for rows.Next() {
		var memID string
		var blob []byte
		var embStale int
		if err := rows.Scan(&memID, &blob, &embStale); err != nil {
			return nil, fmt.Errorf("scan memory embedding row: %w", err)
		}
		vec := blobToVec(blob)
		if len(vec) == 0 {
			continue
		}
		score := dotSimilarity(normQuery, vec)
		if score <= 0 || score < threshold {
			continue
		}
		h.tryPush(memID, score, embStale == 1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	winners := h.drain()
	if len(winners) == 0 {
		return nil, nil
	}

	return s.fetchMemorySearchResultsCtx(ctx, winners)
}

// fetchMemorySearchResults performs the second pass of the two-pass vector
// search: given the top-K (id, score, stale) tuples from the scan pass, it
// fetches the full memory content, tier, and entity_id in a single query.
// Results are returned in the same descending-score order as winners.
// The stale flag from Pass 1 is propagated to MemorySearchResult.StaleEmbedding.
//
// Re-applies expired filter to close the consistency gap between passes:
// a memory valid during Pass 1 could expire before Pass 2 executes.
// Memory-level stale (m.stale=1) is also re-checked — dead memories excluded.
func (s *Store) fetchMemorySearchResults(winners []scoredID) ([]MemorySearchResult, error) {
	return s.fetchMemorySearchResultsCtx(context.Background(), winners)
}

// fetchMemorySearchResultsCtx is the context-aware variant of fetchMemorySearchResults.
func (s *Store) fetchMemorySearchResultsCtx(ctx context.Context, winners []scoredID) ([]MemorySearchResult, error) {
	// Build id → score+position+stale map for reassembly.
	type posScore struct {
		pos   int
		score float64
		stale bool
	}
	lookup := make(map[string]posScore, len(winners))
	placeholders := make([]string, len(winners))
	args := make([]any, len(winners)+1)
	now := time.Now().UTC().Format(time.RFC3339)
	args[0] = now
	for i, w := range winners {
		lookup[w.id] = posScore{pos: i, score: float64(w.score), stale: w.stale}
		placeholders[i] = "?"
		args[i+1] = w.id
	}

	// Pass 2: join memories with their embedding stale flag. The HNSW path
	// doesn't carry stale status, so we always resolve it from SQL here.
	rows, err := s.knowledgeDB.QueryContext(ctx,
		`SELECT m.id, m.content, m.tier, m.entity_id, COALESCE(e.stale, 0)
		 FROM memories m
		 LEFT JOIN memory_embeddings e ON m.id = e.memory_id
		 WHERE m.stale = 0 AND m.expires_at > ?
		   AND m.id IN (`+strings.Join(placeholders, ",")+`)`, args...)
	if err != nil {
		return nil, fmt.Errorf("fetch memory search results: %w", err)
	}
	defer rows.Close()

	results := make([]MemorySearchResult, len(winners))
	for rows.Next() {
		var r MemorySearchResult
		var embStale int
		if err := rows.Scan(&r.MemoryID, &r.Content, &r.Tier, &r.EntityID, &embStale); err != nil {
			return nil, fmt.Errorf("scan memory result: %w", err)
		}
		ps, ok := lookup[r.MemoryID]
		if !ok {
			continue // should not happen
		}
		r.Score = ps.score
		r.StaleEmbedding = embStale == 1
		results[ps.pos] = r
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	// Filter out any zero-value entries (memories deleted between pass 1 and 2).
	n := 0
	for _, r := range results {
		if r.MemoryID != "" {
			results[n] = r
			n++
		}
	}
	return results[:n], nil
}

// memoryEmbeddingDimensions returns the dimensionality of stored embeddings
// by sampling the first row. Returns 0 if no embeddings exist.
// This is used for validation when performing vector search.
func (s *Store) memoryEmbeddingDimensions() int {
	var blob []byte
	err := s.knowledgeDB.QueryRow(`SELECT embedding FROM memory_embeddings LIMIT 1`).Scan(&blob)
	if err != nil {
		return 0
	}
	// Each float32 is 4 bytes.
	return len(blob) / 4
}
