package ingestor

import (
	"context"
	"path/filepath"
	"testing"
	"time"

	"github.com/SynapsesOS/synapses/internal/brain/llm"
	"github.com/SynapsesOS/synapses/internal/brain/store"
)

// TestNew_DefaultTimeout verifies that New() sets a default timeout when
// timeout <= 0 is provided. This exercises the timeout initialization path.
func TestNew_DefaultTimeout(t *testing.T) {
	mock := llm.NewMockClient("")
	st := newTestStore(t)

	// Create ingestor with zero timeout
	ing := New(mock, st, 0)
	if ing.timeout <= 0 {
		t.Errorf("expected default timeout to be set, got %v", ing.timeout)
	}
	if ing.timeout != 3*time.Second {
		t.Errorf("expected default timeout of 3s, got %v", ing.timeout)
	}
}

// TestNew_NegativeTimeout verifies that New() sets a default timeout when
// a negative timeout is provided.
func TestNew_NegativeTimeout(t *testing.T) {
	mock := llm.NewMockClient("")
	st := newTestStore(t)

	ing := New(mock, st, -1*time.Second)
	if ing.timeout != 3*time.Second {
		t.Errorf("expected default timeout of 3s for negative input, got %v", ing.timeout)
	}
}

// TestNew_CustomTimeout verifies that New() preserves a custom timeout when
// a positive value is provided.
func TestNew_CustomTimeout(t *testing.T) {
	mock := llm.NewMockClient("")
	st := newTestStore(t)

	customTimeout := 5 * time.Second
	ing := New(mock, st, customTimeout)
	if ing.timeout != customTimeout {
		t.Errorf("expected custom timeout of %v, got %v", customTimeout, ing.timeout)
	}
}

// TestSummarize_DeterministicSummaryTestHelper verifies that Summarize returns
// a deterministic summary for test helper functions without calling the LLM.
func TestSummarize_DeterministicSummaryTestHelper(t *testing.T) {
	// No LLM call should happen, so a broken mock is fine
	mock := llm.NewMockClient(`{invalid json}`)
	st := newTestStore(t)
	ing := New(mock, st, 3*time.Second)

	resp, err := ing.Summarize(context.Background(), Request{
		ProjectID: "test-project",
		NodeID:    "node:test:TestX",
		NodeName:  "TestX",
		NodeType:  "function",
		Package:   "somepkg_test",
		Code:      "func TestX(t *testing.T) { }",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp.Summary == "" {
		t.Error("expected deterministic summary for test helper")
	}
	if len(resp.Tags) == 0 {
		t.Error("expected tags for test helper")
	}
}

// TestSummarize_DeterministicSummaryGeneratedCode verifies deterministic
// summary for code marked as generated or auto-generated.
func TestSummarize_DeterministicSummaryGeneratedCode(t *testing.T) {
	mock := llm.NewMockClient(`{invalid json}`)
	st := newTestStore(t)
	ing := New(mock, st, 3*time.Second)

	resp, err := ing.Summarize(context.Background(), Request{
		ProjectID: "test-project",
		NodeID:    "node:gen:Generated",
		NodeName:  "Generated",
		NodeType:  "function",
		Package:   "gen",
		Code:      "// Code generated by protoc. Do not edit.\nfunc Generated() {}",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp.Summary == "" {
		t.Error("expected deterministic summary for generated code")
	}
	if len(resp.Tags) == 0 {
		t.Error("expected tags for generated code")
	}
}

// TestSummarize_DeterministicSummaryAccessor verifies deterministic summary
// for simple getter/setter functions.
func TestSummarize_DeterministicSummaryAccessor(t *testing.T) {
	mock := llm.NewMockClient(`{invalid json}`)
	st := newTestStore(t)
	ing := New(mock, st, 3*time.Second)

	resp, err := ing.Summarize(context.Background(), Request{
		ProjectID: "test-project",
		NodeID:    "node:util:GetName",
		NodeName:  "GetName",
		NodeType:  "method",
		Package:   "util",
		Code:      "func (s *Struct) GetName() string { return s.name }",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp.Summary == "" {
		t.Error("expected deterministic summary for accessor")
	}
}

// TestSummarize_StoreError verifies behavior when the store fails to persist
// a summary (though in practice store.SaveSummary rarely fails).
func TestSummarize_StoreError(t *testing.T) {
	// Create a store that will fail operations
	mock := llm.NewMockClient(`{"summary": "Test summary"}`)
	dir := t.TempDir()
	stPath := filepath.Join(dir, "brain.sqlite")

	st, err := store.Open(stPath)
	if err != nil {
		t.Fatalf("open store: %v", err)
	}
	t.Cleanup(func() { st.Close() })

	ing := New(mock, st, 3*time.Second)

	// Close the store to cause subsequent operations to fail
	st.Close()

	// Summarize should now fail because the store is closed
	_, err = ing.Summarize(context.Background(), Request{
		ProjectID: "test-project",
		NodeID:    "node:x",
		NodeName:  "X",
		Code:      "func X() {}",
	})
	if err == nil {
		t.Error("expected error when store is closed, got nil")
	}
}

// TestLooksLikeCode_EdgeCases tests the looksLikeCode edge case detection.
func TestLooksLikeCode_EdgeCases(t *testing.T) {
	testCases := []struct {
		name     string
		code     string
		expected bool
	}{
		{"empty", "", false},
		{"go_shortdecl", "x := 1", true},
		{"comment_only", "// comment", false},
		{"go_funcdef", "func f() {}", true},
		{"assignment", "x = 5", false},
		{"python_def", "def foo(x):", true},
		{"js_arrow", "x => x + 1", false},
		{"js_arrow_body", "() => {}", true},
		{"go_struct", "struct {}", false},
		{"go_struct_with_space", " struct {", true},
		{"go_interface", "interface {}", true},
		{"plain_prose", "This is just some plain text", false},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result := looksLikeCode(tc.code)
			if result != tc.expected {
				t.Errorf("looksLikeCode(%q) = %v, expected %v", tc.code, result, tc.expected)
			}
		})
	}
}

// TestParseSummary_EdgeCases tests the parseSummary edge case paths.
func TestParseSummary_EdgeCases(t *testing.T) {
	testCases := []struct {
		name        string
		input       string
		expectError bool
		checkResult func(t *testing.T, summary string, tags []string)
	}{
		{
			"json_valid",
			`{"summary": "Test"}`,
			false,
			func(t *testing.T, summary string, tags []string) {
				if summary != "Test" {
					t.Errorf("expected 'Test', got %q", summary)
				}
			},
		},
		{
			"plain_text",
			`Simple text response`,
			false,
			func(t *testing.T, summary string, tags []string) {
				if summary != "Simple text response" {
					t.Errorf("expected plain text, got %q", summary)
				}
			},
		},
		{
			"empty_response",
			"",
			true,
			func(t *testing.T, summary string, tags []string) {
				if summary != "" {
					t.Errorf("expected empty on error, got %q", summary)
				}
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			summary, tags, err := parseSummary(tc.input)
			if tc.expectError && err == nil {
				t.Errorf("expected error, got nil")
			}
			if !tc.expectError && err != nil {
				t.Errorf("unexpected error: %v", err)
			}
			tc.checkResult(t, summary, tags)
		})
	}
}
